(UI rebuild) Improved the performance of the query api for Target List with the simplified entities
WebCuratorTool/webcurator pull request #157
Opened 2024-11-14 00:04 UTC by leefrank9527

Improved the performance of the query api for Target List with the simplified entities: created the simplified entities related to the Targets. Only took the fields required by the rest api in the simplified entities to speed up the query performance.

The performance testing data can be found here: https://docs.google.com/document/d/1ut-Xplrd5qE8sBd5Rmv6b5C1d3tYDBspXBdmhALyRmg/edit?usp=drive_link

2024-11-15 12:25 UTC, hannakoppelaar commented on webcurator-core/src/main/java/org/webcurator/domain/TargetDAO.java
> +//    public Pagination searchSummary(final int pageNumber, final int pageSize, final Long searchOid, final String targetName, final Set<Integer> states, final String seed, final String username, fin
This commented out method can probably be removed now?

2024-11-15 12:29 UTC, hannakoppelaar commented on webcurator-db/latest/sql/wct-schema-mysql.sql
> +-- Create a view to speed up the targets query of rest api
I think the view is no longer needed?

2024-11-15 15:19 UTC, hannakoppelaar commented on webcurator-core/src/main/java/org/webcurator/domain/model/simple/SimpleTargetGroup.java
> +    public static final int MAX_TYPE_LENGTH = 255;
Maybe it's better to use the constants from the non-simple variant to avoid duplication of information?

2024-11-15 15:22 UTC, hannakoppelaar requested changes
I've added a few minor remarks in the source code, and I suspect the changes to wct-schema-mysql.sql (the view) are no longer needed and could be rolled back.

2025-02-28 00:28 UTC, leefrank9527 commented
@hannakoppelaar All of your comments were accepted. I rewrote the simplified the entities and the seach api based on the latest fetures/ui-build branch. This experimental pull request and branch will be abandoned. @jeremy-liss @obrienben 
Please see the new pull request: #176

2025-02-28 00:28 UTC, closed without merging